monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - exception

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                max_files: 1
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
when@preprod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: file
                excluded_http_codes: [ 404, 405, 400 ]
            file:
                type: rotating_file
                max_files: 5
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: file
                excluded_http_codes: [ 404, 405, 400 ]
            file:
                type: rotating_file
                max_files: 5
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
