name: 'tcg-api'

services:
  database:
    image: mysql:8.3
    env_file:
      - .env.local
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my_network
  mailer:
    image: dockage/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - my_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - my_network

networks:
  my_network:
    driver: bridge