name: 'tcg-api'

services:
  database:
    image: postgres:12.3
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - my_network
  mailer:
    image: dockage/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - my_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - my_network
    user: "1000:1000"

networks:
  my_network:
    driver: bridge

volumes:
  db_volume:
    name: tcg_database
    driver: local
