# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    booster_open_cooldown_hours: 1
    max_booster_stack: 4

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\BoosterController:
        # No additional arguments needed since it uses BoosterStackService

    App\MessageHandler\UpdateBoosterStackHandler:
        arguments:
            $boosterOpenCooldownHours: '%booster_open_cooldown_hours%'
            $maxBoosterStack: '%max_booster_stack%'

    App\Service\BoosterStackService:
        arguments:
            $boosterOpenCooldownHours: '%booster_open_cooldown_hours%'
            $maxBoosterStack: '%max_booster_stack%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\EventListener\JWTCreatedSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Service\ImageUploaderService:
        arguments:
            $uploadsDirectory: '%kernel.project_dir%/public/uploads'
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'